name: Update usage in README.md

on:
  push:
    branches:
      - master

jobs:
  update_usage:
    name: Update usage in README.md
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install koala-cli
        run: python -m pip install -e .

      - name: Update README
        run: python .github/scripts/update_readme.py

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.head_ref }}
          commit_message: "chore(docs): auto-generate usage & update README.md"
          file_pattern: "README.md"
